[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
defmt = ["dep:defmt", "cookie-cutter/defmt"]

[dependencies]
cookie-cutter = { git = "https://github.com/adinack/embedded-command" }
defmt = { version = "0.3.10", optional = true }
